version: '3.7'

services:
  backend:
    build: Backend
    ports:
      - "3000:3000"
    networks:
      - todo_net
    depends_on:
      - db
  frontend:
    build: Frontend
    ports:
      - "81:80"
    networks:
      - todo_net
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_USER: todolist             
      MYSQL_PASSWORD: todolist-2024  
      MYSQL_DATABASE: todos        
    volumes:      
      - ./DB/ini.sql:/docker-entrypoint-initdb.d/ini.sql
    networks:
      - todo_net

networks:
  todo_net:
    driver: bridge
