version: '3.7'

services:
  web:
    build: Backend
    ports:
      - "3000:3000"
    networks:
      - todo_net
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_USER: todolist             
      MYSQL_PASSWORD: todolist-2024  
      MYSQL_DATABASE: todos        
    volumes:
      - db_data:/var/lib/mysql          
      - ./DB/ini.sql:/docker-entrypoint-initdb.d/ini.sql
    networks:
      - todo_net

networks:
  todo_net:
    driver: bridge

volumes:
  db_data:
